# Generated by Django 2.2.6 on 2019-11-02 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('rumor', models.TextField()),
                ('like_users', models.ManyToManyField(related_name='like_survivors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('rumor', models.TextField()),
                ('like_users', models.ManyToManyField(related_name='like_hunters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
